const jsonProject = [
	{
		type: "radio",
		category: "lorem1",
		question: "lorem ipsum",
		subquestions: ["dolor", "mit", "amet"],
		min: 0,
		max: 100,
		unit: null,
	},
	{
		type: "input",
		category: "lorem1",
		question: "lorem ipsum",
		subquestions: ["dolor", "mit", "amet"],
		min: 0,
		max: 100,
		unit: "km",
	},
	{
		type: "checkbox",
		category: "lorem3",
		question: "lorem ipsum",
		subquestions: ["dolor", "mit", "amet"],
		min: 0,
		max: 100,
		unit: "km",
	},
	{
		type: "radio",
		category: "lorem4",
		question: "lorem ipsum",
		subquestions: ["dolor", "mit", "amet"],
		min: 0,
		max: 100,
		unit: "km",
	},
	{
		type: "range",
		category: "lorem5",
		question: "lorem ipsum",
		subquestions: null,
		min: 0,
		max: 100,
		unit: "km",
	},
];

const employeeConditionalQuestions = [
	// { indexQuestion: 0, type: "radio", ifIsChecked: 0, hide: [1] },
	// { indexQuestion: 2, type: "radio", ifIsChecked: 1, hide: [3] },
	// { indexQuestion: 4, type: "radio", ifIsChecked: 1, hide: [5] },
	// { indexQuestion: 8, type: "radio", ifIsChecked: 1, hide: [9, 10, 11] },
	// {
	// 	indexQuestion: 12,
	// 	type: "checkbox",
	// 	ifIsChecked: 0,
	// 	hide: [13, 14, 15, 16],
	// },
];

const employeeData = [
	{
		id: 1,
		question: "W jaki sposób pracujesz?",
		type: "radio",
		subquestions: "zdalnie;hybrydowo;w biurze",
		category: "ogólne",
		number: 1,
		name: "howWork",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 2,
		question: "Podaj ilość dni w biurze",
		type: "input",
		subquestions: "",
		category: "ogólne",
		number: 2,
		name: "DaysInOffice",
		min: 0,
		max: 31,
		unit: "dni w miesiącu",
	},
	{
		id: 3,
		question: "Czy w pracy odbierasz służbową korespondencję?",
		type: "radio",
		subquestions: "tak;nie",
		category: "ogólne",
		number: 3,
		name: "IsCorr",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 4,
		question: "Ile średnio wysyłasz maili dziennie?",
		type: "input",
		subquestions: "",
		category: "ogólne",
		number: 4,
		name: "NumMail",
		min: 0,
		max: 1000,
		unit: "maili",
	},
	{
		id: 5,
		question: "Czy w pracy odbierasz służbowe telefony?",
		type: "radio",
		subquestions: "tak;nie",
		category: "ogólne",
		number: 5,
		name: "phones",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 6,
		question: "Ile godzin dziennie korzystasz z telefonu służbowego?",
		type: "range",
		subquestions: "",
		category: "ogólne",
		number: 6,
		name: "phoneHours",
		min: 0,
		max: 24,
		unit: "godzin",
	},
	{
		id: 7,
		question: "Ile godzin dziennie pracujesz na:",
		type: "input",
		subquestions: "Laptopie;Komputerze stacjonarnym;Tablecie",
		category: "praca zdalna",
		number: 7,
		name: "hourHorks",
		min: 0,
		max: 24,
		unit: "godzin",
	},
	{
		id: 8,
		question: "Ile godzin dziennie spędzasz na spotkaniach?",
		type: "input",
		subquestions: "",
		category: "praca zdalna",
		number: 8,
		name: "meetingsHours",
		min: 0,
		max: 24,
		unit: "godzin",
	},
	{
		id: 9,
		question: "Czy zamawiasz jedzenie do pracy?",
		type: "radio",
		subquestions: "tak;nie",
		category: "woda i jedzenie",
		number: 9,
		name: "food",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 10,
		question:
			"Ile obiadów zamawiasz z dowozem do firmy średnio w ciągu tygodnia?",
		type: "input",
		subquestions: "",
		category: "woda i jedzenie",
		number: 10,
		name: "numbersOfLunches",
		min: 0,
		max: 100,
		unit: "obiadów",
	},
	{
		id: 11,
		question: "Czy obiady dowożone są zwykle samochodem czy rowerem?",
		type: "radio",
		subquestions: "samochodem;rowerem",
		category: "woda i jedzenie",
		number: 11,
		name: "typeFoodDeliver",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 12,
		question: "Jakiego rodzaju potrawy zamawiasz?",
		type: "radio",
		subquestions: "Mięsne;Wegetariańskie",
		category: "woda i jedzenie",
		number: 12,
		name: "isVege",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 13,
		question: "W jaki sposób dostajesz się do pracy?",
		type: "checkbox",
		subquestions:
			"Samochodem;Autobusem;Tramwajem;Rowerem;Pieszo;Pociągiem;Carpooling;Metrem",
		category: "transport",
		number: 13,
		name: "typeTransport",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 14,
		question: "Ile kilometrów przejeżdzasz do oraz z pracy?",
		type: "input",
		subquestions: "",
		category: "transport",
		number: 14,
		name: "kmWorkDel",
		min: 0,
		max: 1000,
		unit: "km",
	},
	{
		id: 15,
		question: "Jakim typem paliwa zasilany jest Twój samochód?",
		type: "radio",
		subquestions: "Diesel;Benzyna;Energia Elektryczna;Napęd Hybrydowy;LPG",
		category: "transport",
		number: 15,
		name: "fuelCar",
		min: null,
		max: null,
		unit: null,
	},
	{
		id: 16,
		question: "Ile litrów na 100 km statystycznie spala twój samochód?",
		type: "input",
		subquestions: "",
		category: "transport",
		number: 16,
		name: "fuelUsage",
		min: 0,
		max: 20,
		unit: "l/km",
	},
	{
		id: 17,
		question: "Z iloma osobami zwykle podróżujesz?",
		type: "input",
		subquestions: "",
		category: "transport",
		number: 17,
		name: null,
		min: 0,
		max: 10,
		unit: "osobami",
	},
	{
		id: 19,
		question: "Ile godzin lotów służbowych wykonałeś w ciągu roku?",
		type: "input",
		subquestions: "",
		category: "transport",
		number: 18,
		name: "hoursPlane",
		min: 0,
		max: 1000,
		unit: "godzin",
	},
	{
		id: 20,
		question: "Na ilu ekranach pracujesz?",
		type: "input",
		subquestions: "",
		category: "praca zdalna",
		number: 8,
		name: null,
		min: 0,
		max: 5,
		unit: "ekranów",
	},
];

const managerConditionalQuestions = [];

const managerData = [{"id":1,"question":"Ile m2 biur posiada firma?","type":"input","subquestions":"","number":1,"name":"surOffice","min":0,"max":1000,"unit":"m2"},{"id":2,"question":"Ile pracowników pracuje w biurze?","type":"input","subquestions":"","number":2,"name":"numEmp","min":0,"max":10000,"unit":null},{"id":3,"question":"Roczne zużycie energii elektrycznej w kWh","type":"input","subquestions":"","number":3,"name":"annEnergy","min":0,"max":10000,"unit":"kwh"},{"id":4,"question":"jakie są roczne koszty zapłaty za energię elektryczną","type":"input","subquestions":"","number":4,"name":null,"min":0,"max":100000,"unit":"zł"},{"id":5,"question":"Czy energia elektryczna generowana jest z OZE?","type":"radio","subquestions":"tak;nie","number":5,"name":null,"min":null,"max":null,"unit":null},{"id":6,"question":"W ilu % pokrywa zapotrzebowanie?","type":"range","subquestions":"","number":6,"name":null,"min":0,"max":100,"unit":"%"},{"id":7,"question":"Zużycie energii cieplnej w kWh","type":"input","subquestions":"","number":7,"name":null,"min":0,"max":10000,"unit":"kWh"},{"id":8,"question":"Podaj ilość m3 gazu zużytego w ciągu roku","type":"input","subquestions":"","number":8,"name":null,"min":0,"max":10000,"unit":"m3"},{"id":9,"question":"Czy stosujecie w biurze segregację odpadów na plastik, papier, szkło i frakcję BIO ?","type":"radio","subquestions":"tak;nie","number":9,"name":null,"min":null,"max":null,"unit":null},{"id":10,"question":"Ile kg danych śmieci wyrzucanych jest w biurze miesięcznie","type":"range","subquestions":"plastik;szkło;bio;papier","number":10,"name":null,"min":0,"max":100,"unit":"%"},{"id":11,"question":"Ile wynoszą rachunki miesięcznie za wywóz śmieci?","type":"input","subquestions":"","number":11,"name":null,"min":0,"max":1000,"unit":"zł"},{"id":12,"question":"Ile litrów paliwa ze wskazanych rodzajów zostało wykorzystane przez flotę biura w ciągu roku?","type":"input","subquestions":"benzyna;\r\ndiesel;\r\nLPG;\r\nenergia elektryczna","number":12,"name":null,"min":0,"max":10000,"unit":"l"},{"id":13,"question":"Ile wynosi całkowite zużycie wody w biurze?","type":"input","subquestions":"","number":13,"name":null,"min":0,"max":10000,"unit":"l"},{"id":14,"question":"Ile m3 ścieków wyprodukowanych jest w biurze?","type":"input","subquestions":"","number":14,"name":null,"min":0,"max":10000,"unit":"m3"}]